Bringing The ChannelPoint Automatic Reward Redemption to Websocket in…
TwitchLib/TwitchLib.EventSub.Websockets pull request #34
Opened 2024-05-20 02:24 UTC by djinnet

Since the websocket dev branch has been updated to latest changes from dev core in #33 , I do hope it is okay that I am submitted this pull request. Strike while the iron is hot, I suppose. 

Let me know if there are anything that should be modified/changed, so it looks good with the rest of the structure that is already in place.

2024-05-20 09:23 UTC, AoshiW requested changes
you forgot to add the handler to `TwitchLib.EventSub.Websockets.Handler.Channel.ChannelPoints.Redemptions`

2024-05-20 09:23 UTC, AoshiW commented on TwitchLib.EventSub.Websockets/Core/EventArgs/Channel/ChannelPointsAutomaticRewardRedemptionArgs.cs
> +public class ChannelPointsAutomaticRewardRedemptionArgs : TwitchLibEventSubEventArgs<EventSubNotification<ChannelPointsAutomaticRewardRedemption>>
missing new line
```suggestion
namespace TwitchLib.EventSub.Websockets.Core.EventArgs.Channel;

public class ChannelPointsAutomaticRewardRedemptionArgs : TwitchLibEventSubEventArgs<EventSubNotification<ChannelPointsAutomaticRewardRedemption>>
```

2024-05-20 13:03 UTC, djinnet commented
@AoshiW Thanks for letting me know about the handler. I wasnt aware that it need an handler, since I am not entire familiar with the codebase yet.

I tried to make the handler based of ChannelPointsCustomRewardRedemptionAddHandler.cs, but with automatic rewards. 
Seems good?

2024-05-20 14:08 UTC, AoshiW approved these changes
LGTM

2024-06-25 04:31 UTC, djinnet commented
Just out of curiosity, is there more anything that this pull request needs to be tweaked in order to get merged or has it been forgotten to be merged since may? 

I am just asking because last time I touched this pull request was in may and now it is almost at the end of june, so I am little curious.

2024-06-25 15:13 UTC, merged